# -*- coding: utf-8 -*-
"""ESCAPE CHARACTER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUyXp96a4xqucsX5_O1tUIKknWio26Gb
"""

print('Dia berkata: "Pergilah!" ')

print ("Aku menimpali : \"Apakah kau ingin aku 'angkat kaki'?\"")

print ('\\(^_^)/ (\\-_-/)')