# -*- coding: utf-8 -*-
"""JENIS TIPE DATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQYjYYi6FGOO_JYKUeecCOJ_H-3IeXIZ

**Dwi Junita Putri_2411012062**

MEMERIKSA JENIS TIPE DATA
"""

nama = 'dwi'
usia = 21
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""KONVERSI TIPE DATA"""

usia =input('masukkan usia anda ')
print(type(usia))

"""KONVERSI TIPE DATA IMPLISIT"""

a = 5/2
print(type(a))

"""KONVERSI TIPE DATA SECARA NUMERIK

"""

panjang = int(input('masukkan panjang: '))
lebar = float(input('masukkan lebar '))
print('Luas =', panjang * lebar)

"""KONVERSI NUMERIK KE STRING"""

nama ="dwi"
tahun_lahir = 2005
print(nama + ' lahir ditahun ini ' + str(tahun_lahir))