# -*- coding: utf-8 -*-
"""MANIPULASI STRING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhUPuTw6ss1YZgcrPjZ7FXEFYQEH18my

**STRING**
"""

nama = ' DWI JUNITA PUTRI'
npm = ' 2411012062'
prodi = ' BISNIS DIGITAL'

print (nama)
print (npm)

"""**MANIPULASI STRING**"""

print (nama, npm)

print('halo saya', nama, 'dengan npm', npm)

data_lengkap = nama + npm
print (data_lengkap)

data_lengkap_banget = nama + npm + prodi
print (data_lengkap_banget)

"""**STRING + NON STRING**"""

asal_kota = 'bandar lampung'
kode_pos = 35114

asal_kota_dengan_kode_pos = asal_kota + str (kode_pos)

print (asal_kota_dengan_kode_pos)

asal_kota_x3 = asal_kota * 3
print (asal_kota_x3)