# -*- coding: utf-8 -*-
"""Manipulasi String 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWiua3SPreJD9_thbrJ4pbHtJvvOp6Rq

**Operasi in Pada String**
"""

informasi = 'Bahwasannya besok libur sampai tahun depan'

print('sublime text' in informasi)
print('notepad++' in informasi)

"""**Memotong String**"""

nama = 'Dwi Junita Putri'

print(nama [9])
print(nama [6])
print(nama [4])
print(nama [-1])
print(nama [-2])

"""**Slicing String**"""

nama_npm = 'Dwi Junita Putri_2411012062'

print(nama_npm [0:4])
print(nama_npm [4:10])
print(nama_npm [11:16])
print(nama_npm [:-11])
print(nama_npm [-10:])

"""**Menghitung Panjang String**"""

print(len('UNILA'))
print(len('BE STRONG'))

"""**Memeriksa Karakter Awal String**"""

no_npm_1 = '2111111111'
no_npm_2 = '2411333234'
no_npm_3 = '2315834958'

masuk_2024 = '24'

print(no_npm_1.startswith(masuk_2024))
print(no_npm_2.startswith(masuk_2024))
print(no_npm_3.startswith(masuk_2024))

"""**Memeriksa Karakter Akhir String**"""

wapres_asli_tidak_1 = 'fufufafa'
wapres_asli_tidak_2 = 'gibran'

print(wapres_asli_tidak_1.endswith('gibran'))
print(wapres_asli_tidak_2.endswith('gibran'))