# -*- coding: utf-8 -*-
"""MANIPULASI STRING 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TH7Bw5koGt2imrW-L_H_t9vxtfGbEEra
"""

FORMAT SPECIFIERS

nama ='halo, saya %s npm %s'

print(nama % ('dwi junita putri','2411012062'))

template_1 ='halo, saya {nama} npm {npm}'
template_2 ='saya suka {} dan {}'

print (template_1.format(nama = 'dwi junita putri', npm = '2411012062'))
print (template_2.format('makan', 'buah'))

"""STRING INTERPOLATION /F-"""

nama = 'Dwi Junita Putri'
npm = '2411012062'

print (f'Perkenalkan saya {nama} dan npm {npm}')

"""MEMECAHKAN STRING"""

nomor = '1, 2, 3, 4, 5'

print (nomor.split())
print (nomor.split(','))
print (nomor.split(', '))

"""MEMECAHKAN STRING LIST DAN SEBALIKNYA"""

print ('❤️'. join({'aku', 'suka', 'buah'}))

print ('halo o o o o'. upper())

print ('HALO O O O O'. lower())

print('daun dari pohon'.title())
print('POHON ADA AKAR'.title())

print ('Hey Antek Antek Asing' .swapcase())
print ('hiDup joKoWiW' .swapcase())

angka = '12345'

print ('index angka 3:' , angka.find('3'))
print ('index angka 123:' , angka.find('5'))
print ('index angka 5:' , angka.find('3'))

ibu = 'ibu ibu'

print (ibu.replace('u','o'))
print (ibu.replace('i', 'u'))
print (ibu.replace('b', ''))

kalimat = 'Uler melingkar lingkar di atas pagar mutar mutar'
x = kalimat.count('mutar')

print(f'kata "mutar" muncul sebanyak {x} kali')